In [186]:
# Rotate Matrix
# A matrix is a N x N list
# rotate matrix rotates a matrix clock wise 90 degrees

# rotate_mat: list of list of int --> void
# rotate M clock-wise 90 degrees
def rotate_mat(M):
    N = len(M)
    
        
    for n in range(0, N // 2):
        for start in range(n, N-n-1):
            i, j = n, start
            temp = M[i][j]
            
            for k in range(0,4):
                rot_i, rot_j = j, N-1-i
                M[rot_i][rot_j], temp = temp, M[rot_i][rot_j]
                i, j = rot_i, rot_j
                

In [189]:
import numpy as np

def test():
    for i in range(1,11):
        x = np.arange(0, i **2)
        x = x.reshape(i,i)
        rotate_mat(x)
        print(x)

In [190]:
test()

[[0]]
[[2 0]
 [3 1]]
[[6 3 0]
 [7 4 1]
 [8 5 2]]
[[12  8  4  0]
 [13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]]
[[20 15 10  5  0]
 [21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]]
[[30 24 18 12  6  0]
 [31 25 19 13  7  1]
 [32 26 20 14  8  2]
 [33 27 21 15  9  3]
 [34 28 22 16 10  4]
 [35 29 23 17 11  5]]
[[42 35 28 21 14  7  0]
 [43 36 29 22 15  8  1]
 [44 37 30 23 16  9  2]
 [45 38 31 24 17 10  3]
 [46 39 32 25 18 11  4]
 [47 40 33 26 19 12  5]
 [48 41 34 27 20 13  6]]
[[56 48 40 32 24 16  8  0]
 [57 49 41 33 25 17  9  1]
 [58 50 42 34 26 18 10  2]
 [59 51 43 35 27 19 11  3]
 [60 52 44 36 28 20 12  4]
 [61 53 45 37 29 21 13  5]
 [62 54 46 38 30 22 14  6]
 [63 55 47 39 31 23 15  7]]
[[72 63 54 45 36 27 18  9  0]
 [73 64 55 46 37 28 19 10  1]
 [74 65 56 47 38 29 20 11  2]
 [75 66 57 48 39 30 21 12  3]
 [76 67 58 49 40 31 22 13  4]
 [77 68 59 50 41 32 23 14  5]
 [78 69 60 51 42 33 24 15  6]
 [79 70 61 52 43 34 25 16  7]
 [80 71 62 53 44 35 26 17  8]]
[[90 80 70 60 5